version: "3"

tasks:
  flame:
    desc: generate flame graphs
    cmds:
      - sudo cargo flamegraph --profile debug-release -- .
      - sudo cargo flamegraph --profile debug-release --flamechart -o flamechart.svg -- .

  build:
    desc: debug build with cranelift backend, see https://github.com/rust-lang/rustc_codegen_cranelift
    aliases:
      - b
    env:
      CARGO_PROFILE_DEV_CODEGEN_BACKEND: cranelift
      CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER: lld-link.exe
    cmds:
      - cargo +nightly build -Zcodegen-backend

  run:
    desc: debug build and run with cranelift backend, see https://github.com/rust-lang/rustc_codegen_cranelift
    aliases:
      - r
    env:
      CARGO_PROFILE_DEV_CODEGEN_BACKEND: cranelift
      CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER: lld-link.exe
    cmds:
      - cargo +nightly run -Zcodegen-backend
